# Setup
title:               '0xcac'
tagline:             'A Blog'
description:         'No description.'
url:                 https://0xcac.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              '0xcac'
  url:               https://twitter.com/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
